// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vipdggqtknkqvsxpupiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpcGRnZ3F0a25rcXZzeHB1cGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDg3MjQsImV4cCI6MjA2NTkyNDcyNH0.NuHR53m3HW_lSMgUHJio7MM6aI6Vk0MGOP1fiH_Q0cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);